name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 1.0.0)"
        required: true

jobs:
  release:
    name: Release on Windows
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install frontend dependencies
        run: pnpm install # Change to 'npm install' or 'pnpm install' if needed

      # Optional: If you build the frontend separately, add a build command here
      # - name: Build frontend
      #   run: yarn build

      - name: Tauri build and release
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v${{ github.event.inputs.version }}
          releaseName: "PDF Info v${{ github.event.inputs.version }}"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: false
          prerelease: false
