name: Release

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  release:
    name: Release on Windows
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm" # Change to 'npm' or 'pnpm' if needed

      - name: Install frontend dependencies
        run: pnpm install # Change to 'npm install' or 'pnpm install' if needed

      # Optional: If you build the frontend separately, add a build command here
      # - name: Build frontend
      #   run: yarn build

      - name: Tauri build and release
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "App Name v__VERSION__"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false
